name: Build final document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # container: aergus/latex
    steps:
      - uses: actions/checkout@v2
      - run: echo 'Compiling LaTeX document...'
      - run: make 
